# Generated by Django 4.0.3 on 2022-04-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_auto_20210921_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainermsg',
            name='user_type',
            field=models.CharField(blank=True, default='admin', max_length=100),
        ),
    ]
