# Generated by Django 4.0.3 on 2022-04-18 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_trainermsg_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainermsg',
            name='user_type',
        ),
    ]
